version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://admin:DlhRVHYalQv6e06@152.53.55.46:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.3
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "8080:80" # Cambiamos el puerto 80 del host al 8080
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
