services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    environment:
      - PORT=3100
      - MONGO_URI=mongodb://admin:DlhRVHYalQv6e06@152.53.55.46:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.3
    ports:
      - "3100:3100"
    networks:
      - app-network
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "8081:80" # Cambiamos el puerto 80 del host al 8080
      - "8443:443" # Cambiamos el puerto 443 del host al 8443
    networks:
      - app-network
    depends_on:
      - backend
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # Montar certificados SSL
networks:
    app-network:
      driver: bridge
