# Usa una imagen oficial de Node.js para construir el frontend
FROM node:16-alpine AS builder

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para el frontend
COPY ./services-finder-frontend/package*.json ./
RUN npm install
COPY ./services-finder-frontend .

# Construye la aplicación
RUN npm run build

# Usa una imagen de NGINX para servir el frontend
FROM nginx:alpine

# Copia los archivos construidos al servidor NGINX
COPY --from=builder /app/dist /usr/share/nginx/html

# Configuración de NGINX
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expone el puerto 80
EXPOSE 80

# Inicia NGINX
CMD ["nginx", "-g", "daemon off;"]
