# Usa una imagen oficial de Node.js
FROM node:16-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para el backend
COPY ./services-finder-backend/package*.json ./
RUN npm install
COPY ./services-finder-backend .

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar el backend
CMD ["npm", "start"]
